### ISSUE TITLE
Allow updating Boot Disk Size by increasing number on ovc_machine resourse

### ISSUE THREAD

**Issue by katia-e** [gig-tech/terraform-provider-ovc#51] opened 2019-06-24 14:59 UTC
Currently boot disk size of the VM does not update with terraform.
Add possibility to update boot disk when increasing `bootdisk` value in `ovc_machine` resource

**Comment by chrisvdg** [comment] 2019-06-24 15:16
duplicate of #47

**Closed as completed by chrisvdg** 2019-06-24 15:16 UTC
Labels: feature
